- name: Base configuration for all servers
  hosts: all
  become: true

  tasks:
    - name: Update apt
      apt:
        update_cache: yes
      tags: update

    - name: Create user {{ new_user }}
      user:
        name: "{{ new_user }}"
        shell: /bin/bash
        groups: sudo
      tags: users

- name: Install Fail2Ban on all servers
  hosts: all
  become: true
  roles:
    - fail2ban
  tags: security
