---

- name: configure webserver with nginx
  hosts: web
  become: true

  tasks:
    - name: ensure nginx is installed
      package:
        name: nginx
        update_cache: true

    - name: copy nginx config file
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default

    - name: Enable configuration
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: copy home page template
      template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html

    - name: restart nginx
      service:
        name: nginx
        state: restarted

...
